### ISSUE TITLE
Lay out the items vertically instead of horizontally?

### ISSUE THREAD

**Issue by simevidas** [le0pard/browserlist#1]
It may make more sense to arrange the browser versions in a vertical, multi-column list, so that the versions of one browser are in the same column (or across two adjacent columns).

<img width="1280" alt="Screenshot 2021-12-31 at 06 59 00" src="https://user-images.githubusercontent.com/716405/147806315-c8cda230-0cb4-4001-bc06-97f4b5ce72ee.png">

**Comment by le0pard** [comment]
You can try to do this, but I don't think value `>0%` can fit in any screen in multiple vertical columns (some browsers, like "opera mini" have single version)

**Comment by simevidas** [comment]
Sorry if I wasn’t clear. Here’s a screenshot that shows what I meant. I achieved this by using CSS `columns: 4` instead of `display: grid`. Notice how this makes it easier to quickly see which versions of a browser are included.

<img width="1280" alt="Screenshot 2021-12-31 at 20 54 37" src="https://user-images.githubusercontent.com/716405/147837626-0692348a-cfb2-464c-b4c1-d910cb621997.png">

**Comment by le0pard** [comment]
@simevidas ok, now I get it. Yep, looks good. 

As I understand number `columns` will change for different screens, like https://github.com/le0pard/browserlist/blob/fa0f5d0f6a7fb1e80de23378bc00c5e615d66ea3/src/App.svelte#L128-L162 , isn't it?

Will you do PR?

**Comment by le0pard** [comment]
Ok, I did changes. Can you check that it is what you want @simevidas ?

**Comment by simevidas** [comment]
I’m not sure what `display: table` on `.browser-wrapper` does.

The only other thing that probably needs to be changed is the margin on the items.

```css
.browser-wrapper {
  margin: 0 0.5em 1em;
}
```

The way margins work in CSS Multicol is a bit special. The top margin is ignored for the first item of each column except the first one, so if items have a non-zero top margin, the first column will be lower than the other columns. A simple workaround is to not use top margin and to distance the items only with bottom margin.

**Comment by le0pard** [comment]
Big thanks @simevidas Added changes
